# Generated by Django 4.2.5 on 2023-09-16 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Goal')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='update_images/', verbose_name='Image')),
                ('text', models.CharField(max_length=800, verbose_name='Text')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='Goals.goal', verbose_name='Goal')),
            ],
            options={
                'verbose_name': 'Update',
                'verbose_name_plural': 'Updates',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Milestone')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='Goals.goal', verbose_name='Goal')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
            },
        ),
    ]
